# Generated by Django 5.0.3 on 2024-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0003_alter_user_funkos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=128)),
                ('actors', models.ManyToManyField(blank=True, to='funko_api.actor')),
            ],
        ),
    ]
